Algoritmo "Exercicio5"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : JAJA
// Descrição   : Mostrar antecessor e sucessor
// Autor(a)    : Melcksedeck Teyllor
// Data atual  : 14/03/2024
Var
   ant,suce,n : inteiro


Inicio
      Escreval ("Digite seu número: ")
      leia(n)
      ant <- n -1
      suce <- n + 1
      Escreval ("O antecessor de ", n, " é: ")
      escreval(ant)
      Escreval("E o sucessor de ", n, "é: ")
      escreval(suce)


Fimalgoritmo