Algoritmo "Exercicio12"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : JAJA
// Descrição   : Temperatura
// Autor(a)    : Melckseddeck
// Data atual  : 14/03/2024
Var
      gF,gC: real


Inicio
      Escreval("Digite a temperatura em graus Fahrenheit: ")
      leia(gf)
      gC <- 5 * ((gF-32)/9)
      Escreval("A temperatura em graus Celsius é de: ", gC, "°")


Fimalgoritmo