Algoritmo "Exercicio1-C-pg50"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : JAJA
// Descrição   : Escrever numeros divisiveis por 4 menores que 200
// Autor(a)    : Melckseddeck Teyllor
// Data atual  : 09/04/2024
Var
   cont:inteiro


Inicio
      para cont de 1 ate 199 passo 1 faca
           se (cont % 4 = 0) entao
              Escreval(cont)
           fimse
           cont <- cont + 1
      

      fimpara
      

Fimalgoritmo