Algoritmo "Exercicio7-c"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : JAJA
// Descrição   : Calcular volume da lata
// Autor(a)    : Melcksedeck
// Data atual  : 18/03/2024
Var
   volume,raio,altura: real



Inicio

      escreval("Digite a altura da lata:")
      leia(altura)
      escreval("Digite o raio da lata:")
      leia(raio)
      volume <- 3.14 * raio^2 * altura
      Escreval("O volume da lata corresponde a:")
      Escreval(volume)


Fimalgoritmo