Algoritmo "Exercicio7-a"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : JAJA
// Descrição   : Conversão de Temperatura
// Autor(a)    : Melcksedeck
// Data atual  : 18/03/2024
Var
// Seção de Declarações das variáveis 
 gF,gC: real



Inicio
      escreva ("Escreva a temperatura em °C: ")
      leia (gC)
      gF <- (9 * gC + 160)/5
      escreva ( "Essa temperatura corresponde a: ", gF, "° graus Fahrenheit")


Fimalgoritmo