Algoritmo "Exercicio1-C-pag66"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : JAJA
// Descrição   : soma dos 100 primeiros numeros inteiros
// Autor(a)    : Melckseddeck Teyllor
// Data atual  : 10/04/2024
Var
   cont,soma:inteiro

Inicio

      para cont de 1 ate 100 passo 1 faca
           soma <- soma + cont
      fimPara
      Escreval("O resultado da soma dos cem primeiros números inteiros é de: ",soma)

Fimalgoritmo