Algoritmo "Exercicio1-A-pg50"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : JAJA
// Descrição   : quadrados dos numeros inteiros no intervalo de 15 a 200
// Autor(a)    : Melckseddeck Teyllor
// Data atual  : 09/04/2024
Var
   quadrado,cont:inteiro


Inicio
      cont <- 15
      repita
            quadrado <- cont * cont
            Escreval(quadrado)
            cont <- cont + 1
      ate cont > 200


Fimalgoritmo