Algoritmo "Exercicio1-A-pag66"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : JAJA
// Descrição   : quadrados dos numeros inteiros no intervalo de 15 a 200
// Autor(a)    : Melckseddeck Teyllor
// Data atual  : 10/04/2024
Var
   quadrado,cont:inteiro


Inicio

      para cont de 15 ate 200 passo 1 faca
            quadrado <- cont * cont
            Escreval(quadrado)
            cont <- cont + 1
      fimpara


Fimalgoritmo