Algoritmo "Exercicio1-G-pag66"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : JAJA
// Descrição   : Exponenciação
// Autor(a)    : Melckseddeck Teyllor
// Data atual  : 10/04/2024
Var
   cont,valor:inteiro


Inicio
           Escreval("1")
           valor <- 1
      para cont de 1 ate 15 faca
           valor <- valor * 3
           Escreval(valor)
      fimpara

Fimalgoritmo