Algoritmo "Exercicio1-D"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : JAJA
// Descrição   : numeros impares no intervalo de 0 a20
// Autor(a)    : Melcksedeck Teyllor
// Data atual  : 04/04/2024
Var
   contador:inteiro


Inicio
      enquanto (contador < 21) faca
               se (contador % 2 <> 0) entao
                  escreval(contador)
               fimse
               contador <- contador + 1
      fimenquanto


Fimalgoritmo