Algoritmo "exercicio4-I"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : JAJA
// Descrição   : identificar se o numero é impar ou par
// Autor(a)    : Melcksedeck Teyllor
// Data atual  : 02/04/2024
Var
   numero:inteiro


Inicio
      Escreval("Digite um valor inteiro")
      leia(numero)
      
      Se (numero % 2 = 0) entao
         Escreval("O número ",numero," é par")
      senao
           Escreval("O número ",numero," número é impar")
      fimse


Fimalgoritmo