Algoritmo "exercicio1-E-pg66"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : JAJA
// Descrição   :Valores impares no intervalo de 0 a 20
// Autor(a)    : Melckseddeck Teyllor
// Data atual  : 11/04/2024
Var
   cont:inteiro


Inicio
      Escreval("Esses sao os valores impares no intervalo de 0 a 20")
      para cont de 0 ate 20 faca
           Se(cont % 2 <>0)entao
            Escreval(cont)
           fimse
      fimpara


Fimalgoritmo