Algoritmo "Exercicio4-K"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : JAJA
// Descrição   : verificar se numero é maior que 3
// Autor(a)    : Melcksedeck teyllor
// Data atual  : 02/04/2024
Var
   valor:inteiro


Inicio
      Escreval("Digite um valor inteiro: ")
      leia(valor)
      
      se (valor > 3) entao
         Escreval("Esse valor é maior que o esperado")
      senao
           Escreva("Esse foi o valor digitado: ",valor)
      fimse


Fimalgoritmo