Algoritmo "exercicio1-B"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : JAJA
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Melcksedeck Teyllor
// Data atual  : 03/04/2024
Var
 soma, cont:inteiro


Inicio
      soma <- 0
      repita
            soma <- cont + soma
            cont <- cont + 1
      Escreval(soma)
      ate (cont > 100)
      Escreval("O resultado final é : ",soma)
Fimalgoritmo