Algoritmo "Exercicio7-b"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : JAJA
// Descrição   : Conversão de temperatura
// Autor(a)    : Melcksedeck Teyllor
// Data atual  : 18/03/2024
Var


 gF,gC: real



Inicio
      escreva ("Escreva a temperatura em ºF: ")
      leia (gF)
      gC <- 5 / 9 * (gF - 32)
      escreva ( "Essa temperatura corresponde a: ", gC, "° graus Celsius")

Fimalgoritmo